<?php
/*********************************************************************************
 * SugarCRM Community Edition is a customer relationship management program developed by
 * SugarCRM, Inc. Copyright (C) 2004-2013 SugarCRM Inc.

 * SuiteCRM is an extension to SugarCRM Community Edition developed by Salesagility Ltd.
 * Copyright (C) 2011 - 2014 Salesagility Ltd.
 *
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Affero General Public License version 3 as published by the
 * Free Software Foundation with the addition of the following permission added
 * to Section 15 as permitted in Section 7(a): FOR ANY PART OF THE COVERED WORK
 * IN WHICH THE COPYRIGHT IS OWNED BY SUGARCRM, SUGARCRM DISCLAIMS THE WARRANTY
 * OF NON INFRINGEMENT OF THIRD PARTY RIGHTS.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more
 * details.
 *
 * You should have received a copy of the GNU Affero General Public License along with
 * this program; if not, see http://www.gnu.org/licenses or write to the Free
 * Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
 * 02110-1301 USA.
 *
 * You can contact SugarCRM, Inc. headquarters at 10050 North Wolfe Road,
 * SW2-130, Cupertino, CA 95014, USA. or at email address contact@sugarcrm.com.
 *
 * The interactive user interfaces in modified source and object code versions
 * of this program must display Appropriate Legal Notices, as required under
 * Section 5 of the GNU Affero General Public License version 3.
 *
 * In accordance with Section 7(b) of the GNU Affero General Public License version 3,
 * these Appropriate Legal Notices must retain the display of the "Powered by
 * SugarCRM" logo and "Supercharged by SuiteCRM" logo. If the display of the logos is not
 * reasonably feasible for  technical reasons, the Appropriate Legal Notices must
 * display the words  "Powered by SugarCRM" and "Supercharged by SuiteCRM".
 ********************************************************************************/

$relationships = array (
  'aos_quotes_fp_event_locations_1' => 
  array (
    'id' => '183c6d16-d9b4-8f54-e24e-5770e09082be',
    'relationship_name' => 'aos_quotes_fp_event_locations_1',
    'lhs_module' => 'AOS_Quotes',
    'lhs_table' => 'aos_quotes',
    'lhs_key' => 'id',
    'rhs_module' => 'FP_Event_Locations',
    'rhs_table' => 'fp_event_locations',
    'rhs_key' => 'id',
    'join_table' => 'aos_quotes_fp_event_locations_1_c',
    'join_key_lhs' => 'aos_quotes_fp_event_locations_1aos_quotes_ida',
    'join_key_rhs' => 'aos_quotes_fp_event_locations_1fp_event_locations_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => 'default',
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'vend_vendor_fp_event_locations_2' => 
  array (
    'id' => '1b260f93-fd71-e49e-4ad0-5770e0c6df47',
    'relationship_name' => 'vend_vendor_fp_event_locations_2',
    'lhs_module' => 'vend_Vendor',
    'lhs_table' => 'vend_vendor',
    'lhs_key' => 'id',
    'rhs_module' => 'FP_Event_Locations',
    'rhs_table' => 'fp_event_locations',
    'rhs_key' => 'id',
    'join_table' => 'vend_vendor_fp_event_locations_2_c',
    'join_key_lhs' => 'vend_vendor_fp_event_locations_2vend_vendor_ida',
    'join_key_rhs' => 'vend_vendor_fp_event_locations_2fp_event_locations_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => 'default',
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'rgn_region_fp_event_locations' => 
  array (
    'id' => '25552850-abdc-04dc-67ba-5770e0ddb5e8',
    'relationship_name' => 'rgn_region_fp_event_locations',
    'lhs_module' => 'Rgn_Region',
    'lhs_table' => 'rgn_region',
    'lhs_key' => 'id',
    'rhs_module' => 'FP_Event_Locations',
    'rhs_table' => 'fp_event_locations',
    'rhs_key' => 'id',
    'join_table' => 'rgn_region_fp_event_locations_c',
    'join_key_lhs' => 'rgn_region_fp_event_locationsrgn_region_ida',
    'join_key_rhs' => 'rgn_region_fp_event_locationsfp_event_locations_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
    'from_studio' => true,
  ),
  'fp_events_fp_event_locations_1' => 
  array (
    'id' => '2aacb30a-0f3f-8005-7792-5770e0fe0474',
    'relationship_name' => 'fp_events_fp_event_locations_1',
    'lhs_module' => 'FP_events',
    'lhs_table' => 'fp_events',
    'lhs_key' => 'id',
    'rhs_module' => 'FP_Event_Locations',
    'rhs_table' => 'fp_event_locations',
    'rhs_key' => 'id',
    'join_table' => 'fp_events_fp_event_locations_1_c',
    'join_key_lhs' => 'fp_events_fp_event_locations_1fp_events_ida',
    'join_key_rhs' => 'fp_events_fp_event_locations_1fp_event_locations_idb',
    'relationship_type' => 'many-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => 'default',
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'fp_event_locations_accounts_1' => 
  array (
    'id' => '3f19d79e-dfb7-261b-5a4a-5770e0c3f39e',
    'relationship_name' => 'fp_event_locations_accounts_1',
    'lhs_module' => 'FP_Event_Locations',
    'lhs_table' => 'fp_event_locations',
    'lhs_key' => 'id',
    'rhs_module' => 'Accounts',
    'rhs_table' => 'accounts',
    'rhs_key' => 'id',
    'join_table' => 'fp_event_locations_accounts_1_c',
    'join_key_lhs' => 'fp_event_locations_accounts_1fp_event_locations_ida',
    'join_key_rhs' => 'fp_event_locations_accounts_1accounts_idb',
    'relationship_type' => 'many-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => 'default',
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'contacts_fp_event_locations_1' => 
  array (
    'id' => '4960c0dc-e3c5-d168-02a5-5770e086f7b4',
    'relationship_name' => 'contacts_fp_event_locations_1',
    'lhs_module' => 'Contacts',
    'lhs_table' => 'contacts',
    'lhs_key' => 'id',
    'rhs_module' => 'FP_Event_Locations',
    'rhs_table' => 'fp_event_locations',
    'rhs_key' => 'id',
    'join_table' => 'contacts_fp_event_locations_1_c',
    'join_key_lhs' => 'contacts_fp_event_locations_1contacts_ida',
    'join_key_rhs' => 'contacts_fp_event_locations_1fp_event_locations_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => 'default',
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'sku_sku_fp_event_locations_1' => 
  array (
    'id' => '538ca9ff-3467-8aaf-b553-5770e03f4633',
    'relationship_name' => 'sku_sku_fp_event_locations_1',
    'lhs_module' => 'sku_SKU',
    'lhs_table' => 'sku_sku',
    'lhs_key' => 'id',
    'rhs_module' => 'FP_Event_Locations',
    'rhs_table' => 'fp_event_locations',
    'rhs_key' => 'id',
    'join_table' => 'sku_sku_fp_event_locations_1_c',
    'join_key_lhs' => 'sku_sku_fp_event_locations_1sku_sku_ida',
    'join_key_rhs' => 'sku_sku_fp_event_locations_1fp_event_locations_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'fp_event_locations_aos_quotes_1' => 
  array (
    'id' => '6fe21d6e-2af8-98e9-e8a1-5770e0657493',
    'relationship_name' => 'fp_event_locations_aos_quotes_1',
    'lhs_module' => 'FP_Event_Locations',
    'lhs_table' => 'fp_event_locations',
    'lhs_key' => 'id',
    'rhs_module' => 'AOS_Quotes',
    'rhs_table' => 'aos_quotes',
    'rhs_key' => 'id',
    'join_table' => 'fp_event_locations_aos_quotes_1_c',
    'join_key_lhs' => 'fp_event_locations_aos_quotes_1fp_event_locations_ida',
    'join_key_rhs' => 'fp_event_locations_aos_quotes_1aos_quotes_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => 'default',
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'fp_event_locations_vmrfq_vmrfq_1' => 
  array (
    'id' => '715f707d-f1b9-167e-36db-5770e0233c70',
    'relationship_name' => 'fp_event_locations_vmrfq_vmrfq_1',
    'lhs_module' => 'FP_Event_Locations',
    'lhs_table' => 'fp_event_locations',
    'lhs_key' => 'id',
    'rhs_module' => 'VMRFQ_VMRFQ',
    'rhs_table' => 'vmrfq_vmrfq',
    'rhs_key' => 'id',
    'join_table' => 'fp_event_locations_vmrfq_vmrfq_1_c',
    'join_key_lhs' => 'fp_event_locations_vmrfq_vmrfq_1fp_event_locations_ida',
    'join_key_rhs' => 'fp_event_locations_vmrfq_vmrfq_1vmrfq_vmrfq_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => 'default',
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'fp_event_locations_fp_events_1' => 
  array (
    'id' => '86d5cb09-f66c-a184-12be-5770e05bd6fe',
    'relationship_name' => 'fp_event_locations_fp_events_1',
    'lhs_module' => 'FP_Event_Locations',
    'lhs_table' => 'fp_event_locations',
    'lhs_key' => 'id',
    'rhs_module' => 'FP_events',
    'rhs_table' => 'fp_events',
    'rhs_key' => 'id',
    'join_table' => 'fp_event_locations_fp_events_1_c',
    'join_key_lhs' => 'fp_event_locations_fp_events_1fp_event_locations_ida',
    'join_key_rhs' => 'fp_event_locations_fp_events_1fp_events_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'fp_event_locations_modified_user' => 
  array (
    'id' => '9c7d5868-4f1f-7ca7-c539-5770e0b350b2',
    'relationship_name' => 'fp_event_locations_modified_user',
    'lhs_module' => 'Users',
    'lhs_table' => 'users',
    'lhs_key' => 'id',
    'rhs_module' => 'FP_Event_Locations',
    'rhs_table' => 'fp_event_locations',
    'rhs_key' => 'modified_user_id',
    'join_table' => NULL,
    'join_key_lhs' => NULL,
    'join_key_rhs' => NULL,
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => true,
  ),
  'fp_event_locations_leads_1' => 
  array (
    'id' => 'a24f5d79-d511-a005-3d49-5770e0d9ae4b',
    'relationship_name' => 'fp_event_locations_leads_1',
    'lhs_module' => 'FP_Event_Locations',
    'lhs_table' => 'fp_event_locations',
    'lhs_key' => 'id',
    'rhs_module' => 'Leads',
    'rhs_table' => 'leads',
    'rhs_key' => 'id',
    'join_table' => 'fp_event_locations_leads_1_c',
    'join_key_lhs' => 'fp_event_locations_leads_1fp_event_locations_ida',
    'join_key_rhs' => 'fp_event_locations_leads_1leads_idb',
    'relationship_type' => 'many-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => 'default',
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'fp_event_locations_created_by' => 
  array (
    'id' => 'a8bf4fef-38ac-a913-5e7c-5770e00c9963',
    'relationship_name' => 'fp_event_locations_created_by',
    'lhs_module' => 'Users',
    'lhs_table' => 'users',
    'lhs_key' => 'id',
    'rhs_module' => 'FP_Event_Locations',
    'rhs_table' => 'fp_event_locations',
    'rhs_key' => 'created_by',
    'join_table' => NULL,
    'join_key_lhs' => NULL,
    'join_key_rhs' => NULL,
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => true,
  ),
  'aos_quotes_fp_event_locations_2' => 
  array (
    'id' => 'ae65190f-d270-94ca-9cff-5770e0a12bd0',
    'relationship_name' => 'aos_quotes_fp_event_locations_2',
    'lhs_module' => 'AOS_Quotes',
    'lhs_table' => 'aos_quotes',
    'lhs_key' => 'id',
    'rhs_module' => 'FP_Event_Locations',
    'rhs_table' => 'fp_event_locations',
    'rhs_key' => 'id',
    'join_table' => 'aos_quotes_fp_event_locations_2_c',
    'join_key_lhs' => 'aos_quotes_fp_event_locations_2aos_quotes_ida',
    'join_key_rhs' => 'aos_quotes_fp_event_locations_2fp_event_locations_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => 'default',
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'aos_quotes_fp_event_locations_3' => 
  array (
    'id' => 'ae92b694-5be6-3f91-d692-5770e06e72b4',
    'relationship_name' => 'aos_quotes_fp_event_locations_3',
    'lhs_module' => 'AOS_Quotes',
    'lhs_table' => 'aos_quotes',
    'lhs_key' => 'id',
    'rhs_module' => 'FP_Event_Locations',
    'rhs_table' => 'fp_event_locations',
    'rhs_key' => 'id',
    'join_table' => 'aos_quotes_fp_event_locations_3_c',
    'join_key_lhs' => 'aos_quotes_fp_event_locations_3aos_quotes_ida',
    'join_key_rhs' => 'aos_quotes_fp_event_locations_3fp_event_locations_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => 'default',
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'fp_event_locations_assigned_user' => 
  array (
    'id' => 'b2f1652f-d9f5-48c9-5598-5770e0d485ea',
    'relationship_name' => 'fp_event_locations_assigned_user',
    'lhs_module' => 'Users',
    'lhs_table' => 'users',
    'lhs_key' => 'id',
    'rhs_module' => 'FP_Event_Locations',
    'rhs_table' => 'fp_event_locations',
    'rhs_key' => 'assigned_user_id',
    'join_table' => NULL,
    'join_key_lhs' => NULL,
    'join_key_rhs' => NULL,
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => true,
  ),
  'abc12_data_fp_event_locations_1' => 
  array (
    'id' => 'd34746bb-81d8-5481-1755-5770e04d6ed6',
    'relationship_name' => 'abc12_data_fp_event_locations_1',
    'lhs_module' => 'abc12_Data',
    'lhs_table' => 'abc12_data',
    'lhs_key' => 'id',
    'rhs_module' => 'FP_Event_Locations',
    'rhs_table' => 'fp_event_locations',
    'rhs_key' => 'id',
    'join_table' => 'abc12_data_fp_event_locations_1_c',
    'join_key_lhs' => 'abc12_data_fp_event_locations_1abc12_data_ida',
    'join_key_rhs' => 'abc12_data_fp_event_locations_1fp_event_locations_idb',
    'relationship_type' => 'many-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => 'default',
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'fp_event_locations_accounts_2' => 
  array (
    'id' => 'df90f02a-7b7b-a6f4-68ef-5770e0c1cd0b',
    'relationship_name' => 'fp_event_locations_accounts_2',
    'lhs_module' => 'FP_Event_Locations',
    'lhs_table' => 'fp_event_locations',
    'lhs_key' => 'id',
    'rhs_module' => 'Accounts',
    'rhs_table' => 'accounts',
    'rhs_key' => 'id',
    'join_table' => 'fp_event_locations_accounts_2_c',
    'join_key_lhs' => 'fp_event_locations_accounts_2fp_event_locations_ida',
    'join_key_rhs' => 'fp_event_locations_accounts_2accounts_idb',
    'relationship_type' => 'many-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => 'default',
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'fp_event_locations_aos_quotes_2' => 
  array (
    'rhs_label' => 'Quotes',
    'lhs_label' => 'Address',
    'rhs_subpanel' => 'default',
    'lhs_module' => 'FP_Event_Locations',
    'rhs_module' => 'AOS_Quotes',
    'relationship_type' => 'one-to-many',
    'readonly' => true,
    'deleted' => false,
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => true,
    'relationship_name' => 'fp_event_locations_aos_quotes_2',
  ),
);